apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp-pod-nginx
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
    
