apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # this defines which pods are going to be represented by this service
  # the service becomes a network endpoint for either services
  # or maybe external users to connect to (eg. browser)
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort
# kubectl apply -f first-service.yaml

