apiVersion: v1
kind: Service
metadata:
  name: myapp-service-clusterIP
  labels:
    tier: service-tutorial
spec:
  type: ClusterIP
  ports:
    - port: 80          
      targetPort: 80 
  selector:
    app: myapp