apiVersion: v1
kind: Service
metadata:
  name: myapp-service-v1
  labels:
    tier: service-tutorial
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: myapp