apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    tier: service-tutorial
spec:
  type: LoadBalancer
  ports:
    - port: 80          
      targetPort: 80    
      nodePort: 30008   
  selector:
    app: myapp