apiVersion: v1
kind: Service
metadata:
  name: myapp-service-nodePort
  labels:
    tier: service-tutorial
spec:
  type: NodePort
  ports:
    - port: 80          # port on the pod/container
      targetPort: 80    # port on the service
      nodePort: 30008   # port on the node
  selector:
    app: myapp