apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset-demo
  labels:
    app: myapp
    tier: handson-replicaset
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx-2-tutorial-kubernetes
          image: nginx