apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp #name of replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata: # template for the pod
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
